### ISSUE TITLE
Configurable redirect_uri in GoogleDrive.saved_session

### ISSUE THREAD

**Issue by fbehrens** [gimite/google-drive-ruby#149]
I am not very solid in oauth2, so I am happy to have done the migration from 0.3 to 1.0.1 with oauth2 with a save session that runs on heroku. To get the token i had to mokeypatch the gem to set my working `redirect_uri` because the default one was not working.

    # auth.redirect_uri = "urn:ietf:wg:oauth:2.0:oob"
    auth.redirect_uri = "http://www.rhythmuswelten.de/"

So I suggest that being another parameter, and maybe keyword arguments,
would provide a pull request if there is positive feedback

**Comment by gimite** [comment]
Do you provide your own client ID / secret, or do you just use the default one? If you provide your own, did you choose "Installed application" as the application type when you create the ID?

If you choose "Installed application" or you use the default one, auth.redirect_uri = "urn:ietf:wg:oauth:2.0:oob" should work. It worked for me. And I believe it must be "urn:ietf:wg:oauth:2.0:oob" to let the auth page to show the auth code, so that you can paste in the terminal.

**Comment by fbehrens** [comment]
I choose "Client ID for Web-Application", as i didn't know what to do with the private key.

    session = GoogleDrive.saved_session \
      ".ruby_google_drive.token",#path
      nil,#proxy
      ENV['GOOGLE_CLIENT_ID'],
      ENV['GOOGLE_CLIENT_SECRET']

yields an error when visiting the suggested url.
After I changed the redirect_url in the gem source to a page I own, it was working (the credentials were stored, and could be used again). 

The code was not displayed on the page, but could be copied from the browser url after I was redirected to my page. Was looking somewhat like 

    http://www.rhythmuswelten.de?code=.........

**Comment by gimite** [comment]
As mentioned above, you must choose "Installed application", not "Web application" or "Service account", as the application type. Then I believe you won't be asked for a private key.

**Comment by fbehrens** [comment]
Yes, I see, thanks
