### ISSUE TITLE
cannot load such file -- google/api_client

### ISSUE THREAD

**Issue by abhiramm** [gimite/google-drive-ruby#167]
After including google drive gem in my gem file and starting rails c.

Am getting this error,

cannot load such file -- google/api_client

/usr/local/rvm/gems/ruby-2.1.1/gems/google_drive-1.0.1/lib/google_drive.rb:5:in `require': cannot load such file -- google/api_client (LoadError)
	from /usr/local/rvm/gems/ruby-2.1.1/gems/google_drive-1.0.1/lib/google_drive.rb:5:in `<top (required)>'

How to solve it.

**Comment by rossta** [comment]
There appear to be breaking changes in `google-api-client` version `0.9.x`. Trying using to `gem 'google-api-client` < 0.9` in your Gemfile if you're using bundler.

**Comment by arifkalayci** [comment]
This solves the problem, but it should look like gem `google-api-client', '<0.9'`

**Comment by lunrfarsde** [comment]
This solves the problem, but it should look like `gem google-api-client', '<0.9'`

**Comment by gimite** [comment]
Thanks for the report and sorry for late. I made the suggested change in the repository. Since google-api-client 0.9 is still in prerelease, I believe the issue only impacts people who have installed google-api-client with --prerelease option. I will migrate to 0.9 after it is officially released.

FYI I also filed an issue against google-api-client to call the new version 1.0 instead of 0.9: https://github.com/google/google-api-ruby-client/issues/301
