### ISSUE TITLE
Service account instructions seem not to work correctly

### ISSUE THREAD

**Issue by acjay** [gimite/google-drive-ruby#234]
I tried following the authentication instructions for a service account, but got the following error:

```
irb(main):003:0> session = GoogleDrive::Session.from_config("blah_blah.json")
ArgumentError: client_id and client_secret must be both specified or both omitted
```

I'm using the raw JSON file straight from Google. I selected "AppEngine default service account", in case that matters. I noticed the JSON file didn't include a `client_secret` field. I tried removing `client_secret`, and error went away, prompting me to enter a link into my browser. But this seems to have authenticated the session with my own Google account, not a service account, because the files I listed from the session were my own. I'm new to this but my understanding is this isn't supposed to be the case, but that the service account is like it's own separate file space.

Sorry to ask a trivial question as an issue, but maybe I'm making a mistake or there's a step missing.

**Comment by gimite** [comment]
You must use from_service_account_key instead of from_config. Both the service account key file and the config file are JSON file, so it's confusing, but they are incompatible.

The usage of service account is documented here:
https://github.com/gimite/google-drive-ruby/blob/master/doc/authorization.md#on-behalf-of-no-existing-users-service-account
If you find a document of **service account** using from_config, it's a document bug, so let me know :)

It should probably output more friendly error message for this kind of mistake...

**Comment by acjay** [comment]
Yeah, if you delete the `client_id` field, it proceeds happily, and actually ends up rewriting the JSON file.

**Comment by gimite** [comment]
If you use from_service_account_key, you should be able to use the downloaded JSON file as is.
