### ISSUE TITLE
Worksheet loads cells on save even if only title changed

### ISSUE THREAD

**Issue by artemas** [gimite/google-drive-ruby#240]

**Comment by gimite** [comment]
Thanks for the report.

That's probably because Worksheet#save calls max_rows and max_cols:
https://github.com/gimite/google-drive-ruby/blob/master/lib/google_drive/worksheet.rb#L313
It's probably fixed by just omitting gs:rowCount and gs:colCount if the cells are not loaded. Feel free to send a pull request for it :)

**Comment by artemas** [comment]
Propose to have the ability to change max values without loading cells.
