### ISSUE TITLE
State parameter for dynamic redirect URI or arbitrary params

### ISSUE THREAD

**Issue by feliperaul** [gimite/google-drive-ruby#252]
Google does not allow wildcards or dynamic redirect URIs.

The solution everybody uses is to pass whatever arbitrary parameter you want in the `state` param when making the auth request: http://stackoverflow.com/questions/7722062/google-oauth2-redirect-uri-with-several-parameters

How can I access this param using the gem? I searched the docs and github issues and couldn't find anything.

**Comment by gimite** [comment]
It would be actually a question to googleauth library because google_drive just relies on the library for OAuth flow.

But I found that there is Signet::OAuth2::Client#state= method (Google::Auth::UserRefreshCredentials is a subclass of Signet::OAuth2::Client):
http://www.rubydoc.info/github/google/signet/Signet/OAuth2/Client#state%3D-instance_method
So I guess you can write:

```ruby
credentials.state = "your_state_param"
credentials.authorization_uri
```

But I haven't tried it myself.

**Comment by feliperaul** [comment]
@gimite worked flawlessly, I can get the params I set back using `params[:state]` in the return url action. 
Thank you.

**Comment by javaone199** [comment]
Tried adding state param to redirect URL:

Error 400: invalid_request
Invalid redirect_uri contains reserved response param state
