### ISSUE TITLE
collection_by_title.add is adding files to the collection and to the root path

### ISSUE THREAD

**Issue by EGimenoS** [gimite/google-drive-ruby#260]
Hi, first of all thank you for your work with this gem.

I have writen a script to lookup for documents with a given date and upload them to Google Drive. I have 2 different folders, and I access them using collection_by_title. The problem is that the files are being uploaded each one two times, one to the folder I want and another one to the root path of my GDrive. Any thoughts?

This is the method where the file gets uploaded:

```
def subir_albaran(file, serie)
	folder = @session.collection_by_title("#{serie}")
	ruta = "#{@basedir}/#{serie}/#{file}"
	folder.add(@session.upload_from_file(ruta, file, convert: false))
end
```

**Comment by gimite** [comment]
You also need to remove the file from the root collection.

```ruby
file = @session.upload_from_file(ruta, file, convert: false)
folder.add(file)
@session.root_collection.remove(file)
```

Because the file is uploaded to the root collection by default. And a file can belong to multiple collections, and Collection#add just adds a file to the collection, but it doesn't remove it from the original collection. (Note that, if you drag&drop a file on web UI, it **moves** the file i.e., it performs both add and remove.)

**Comment by EGimenoS** [comment]
That exactly worked Hiroshi, thanks a lot.
