### ISSUE TITLE
any way to send pageSize parameter = 1000?

### ISSUE THREAD

**Issue by Lemez** [gimite/google-drive-ruby#279]
Hi,

I love this library, thank you. I am using to store images (currently 700), and have tried:
1) page_token method with end / while block, as mentioned in the docs
2) splitting the images into subcollections which I then access on  a folder by folder basis.

The problem is that iterating 100 or fewer files at a time is slow:  it is takes ~3 minutes to load 700 images at the moment (as they are in many subcollections (each of which is currently sent as a separate request), and I would like to store 1000s.

Is there any way to be able to increase pageSize to 1000, as detailed [here](https://developers.google.com/drive/v3/reference/files/list)?

Thank you.

**Comment by gimite** [comment]
I haven't confirmed but I guess you can do like this?:
```ruby
session.files(page_size: 1000)
```

**Comment by Lemez** [comment]
I tried that, but it only seems to work if the value is < 100:

ie
session.files(page_size: 90)

works as expected, but for any value > 100.



================
http://lemez.net

**Comment by Lemez** [comment]
Alternately, I see that session.files on root folder gets ALL the files to any level depth, not just the first level.

Is there any way to get this behaviour from a different folder to ROOT?

**Comment by gimite** [comment]
I found that the API returns up to 100 files if fields: "*" is specified, which is default of Session#files. I couldn't find any document mentioning it, though. You can write:
```ruby
session.files(page_size: 1000, fields: nil)
```
to get 1000 files, but some of the methods of the returned files are not available because the result contains only subset of fields.

> Is there any way to get this behaviour from a different folder to ROOT? (this is really a separate question, I can move it to a new issue if you prefer).

You mean you want to get all the files under a specific folder, including those in its subfolders? I don't think it's possible with a single operation. You need to iterate over all subfolders recursively by yourself.
