### ISSUE TITLE
Sign in with Google temporarily disabled for this app 

### ISSUE THREAD

**Issue by diegodurs** [gimite/google-drive-ruby#357]
<img width="650" alt="Capture d’écran 2019-12-02 à 11 45 46" src="https://user-images.githubusercontent.com/1175676/69944880-5f822b80-14f9-11ea-836b-3ace33846777.png">

When proceeding with the setup of credentials, when I do the first step "1. Open this page:", I then click on my profile with which I want to login, then I get this error message... 

Any clue why ? This seems new as I used this gem before.

**Comment by gimite** [comment]
Are you using your own OAuth client ID following one of the instructions here:
https://github.com/gimite/google-drive-ruby/blob/master/doc/authorization.md
or do you use the default client ID provided by the library?

If the former, you need to let your client ID verified by Google to remove the warning. See:
https://stackoverflow.com/questions/50509667/sign-in-with-google-temporarily-disabled-for-this-app

If the latter then it's expected that the warning is shown, because the ID is used by arbitrary people. I believe there is a link in the page to ignore the warning and go forward. But it may have been removed?

**Comment by snex** [comment]
I have tried both and I am receiving the error with both.

**Comment by gimite** [comment]
Yeah it looks like the case.

In that case, you need to go with the former option and do:
> If the former, you need to let your client ID verified by Google to remove the warning. See:
https://stackoverflow.com/questions/50509667/sign-in-with-google-temporarily-disabled-for-this-app

Note that you can skip the verification if your app is used by less than 100 users. See "What app types are not applicable for verification?" in https://support.google.com/cloud/answer/9110914 . Even in that case you may still need to explicitly enumerate required scopes in this setting page:
https://console.developers.google.com/apis/credentials/consent/edit

**Comment by snex** [comment]
This app is used only by me, do you know how to hand this information off to Google so that I can skip the verification process? I don't seem to see anywhere I can request a skip.

**Comment by gimite** [comment]
See my previous comment which exactly points to the process to skip the verification.

**Comment by snex** [comment]
I must be missing something, because the only things I see related to this are talking about putting projects in Organizations, which require all sorts of other verifications such as owning a domain name. I don't have any domain name. I am just trying to run a simple command line script, which worked fine less than a week ago without having to do any of this nonsense.

**Comment by gimite** [comment]
This is the part in the doc relevant to you:

> You do not need to submit your app for review if it's going to be used in any of the following scenarios:
>
> Personal Use: The app is not shared with anyone else or will be used by fewer than 100 users. Hence, you can continue using the app by bypassing the unverified app warning during sign-in.

It means that you cannot remove the warning, but instead the warning page shows a small link which allows you to ignore the warning as it used to do, if the app has less than 100 users.

Note that, as I wrote above, you probably still need to explicitly enumerate required scopes in this setting page:
https://console.developers.google.com/apis/credentials/consent/edit
otherwise the link to bypass the warning may not show up.

**Comment by ivanovaleksey** [comment]
@snex I have faced with the similar problem.
You just need to create Content Screen with name and scopes (no domain and all that complex things). And then just press Save.
No need to publish for verification. After that Google will provide you with client id & secret.
Put these credentials in json config file as described in [docs](https://github.com/gimite/google-drive-ruby/blob/master/doc/authorization.md) and then go to authorize your app.
Just like @gimite said, it would notify you about security risk but there would be _Advanced_ link to proceed anyway.
P.S. @gimite thank for the help and explanations!

**Comment by snex** [comment]
@ivanovaleksey I have done all that, and it does not work. I clicked the Advanced link to proceed and it just goes back to the same error reported in the Issue.

**Comment by ivanovaleksey** [comment]
@snex are you sure you authorize in your newly created app and not in old _google-drive-ruby_ default app?
Check client id & secret in your json config file. Make sure that this file exists because in other way the gem [would try to authorize](https://github.com/gimite/google-drive-ruby/blob/master/lib/google_drive/session.rb#L146) access with it's credentials (maybe this behaviour should now be changed). And this would lead to the error you get.

**Comment by snex** [comment]
@ivanovaleksey ugh.. problem turned out to be the config.json was in a different folder than expected and the script simply wasn't reading it and defaulting to the original credentials. I still agree that if those credentials don't work, they should just not be provided at all, as they used to work and it caused a whole lot of confusion when it just suddenly stopped for no reason.

**Comment by ivanovaleksey** [comment]
@snex yes, defaulting to these credentials now can be confusing. @gimite what do you think about that?

**Comment by gimite** [comment]
Sorry for late. Yeah I agree that the default credential should be removed. I will work on it.

**Comment by gimite** [comment]
I removed the default credential at google_drive 3.0.4.
